### ISSUE TITLE
meme which have not been added in mkdocs.yml and index.md

### ISSUE THREAD

**Issue by WillHouMoe** [WillHouMoe/c1-wiki#42]
eldone-out.md
eg-de.md
the-f-word.md

**Comment by Owencjs** [comment]
and something hasn't been created files:
人多的地方不要去
被坏人抓走
桃子_____
你在浏览
忘记了&不知道&都一样&差不多
USTALAUF
右是哪边
@WillHouMoe

**Comment by WillHouMoe** [comment]
teacher-wang
out-of-shape

**Comment by WillHouMoe** [comment]
用不着了。
